# syntax=docker/dockerfile:1

##
## Build
##
FROM golang:1.16-buster AS build

WORKDIR /app

COPY go.mod ./
RUN go mod download

COPY *.go ./
COPY static ./static

RUN go build -o /go-server

RUN chmod a+x /go-server


##
## Deploy
##
FROM gcr.io/distroless/base-debian10

WORKDIR /

COPY --from=build /go-server /go-server

EXPOSE 8080

USER nonroot:nonroot

ENTRYPOINT ["/go-server"]
